apiVersion: v1
kind: Service
metadata:
  name: master-service
  namespace: blockchain-microservices
  labels:
    app: master-service
spec:
  selector:
    app: master-service
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: requester-service
  namespace: blockchain-microservices
  labels:
    app: requester-service
spec:
  selector:
    app: requester-service
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: provider-service
  namespace: blockchain-microservices
  labels:
    app: provider-service
spec:
  selector:
    app: provider-service
  ports:
  - port: 5004
    targetPort: 5004
    protocol: TCP
  type: LoadBalancer 